# Generated by Django 5.2.10 on 2026-02-12 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinvitation',
            name='invited_user',
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='email',
            field=models.EmailField(default='dummy@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
