# Generated by Django 5.2.10 on 2026-01-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='members',
        ),
    ]
