# Generated by Django 5.2.10 on 2026-02-13 23:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0005_taskattachmenent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskAttachmenent',
            new_name='TaskAttachment',
        ),
    ]
