# Generated by Django 5.2.10 on 2026-04-29 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0011_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projectmanager.task'),
        ),
    ]
